spring.application.name=SIARSP

# Server settings
server.address=0.0.0.0
server.port=8080
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=tomcat
spring.thymeleaf.encoding=UTF-8

# DB settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:mysql://mysql-8.4.local:3306/PNEUMOTRAINING?characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=
hibernate.validator.apply_to_ddl=true

# Resources settings
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
spring.devtools.restart.additional-paths=src/main/resources/templates,src/main/resources/static

# Logging settings
logging.level.root=INFO
logging.pattern.console=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n

# Mail settings
spring.mail.host=smtp.rambler.ru
spring.mail.username=4ygyn007@rambler.ru
spring.mail.password=uhtrbCGFHNFYws12
spring.mail.port=465
spring.mail.protocol=smtps
mail.debug=true

server.tomcat.max-part-count=100